openapi: "3.0.0"
info:
  title: 'DTOs'
  version: 1.0.0
paths:
  /dummy:
    get:
      responses:
        '200':
          description: 'Dummy'
components:
  schemas:
    AuthenticationRequestDto:
      type: object
      description: 'Request for user auth'
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    AccessDto:
      type: object
      description: 'Bearer token for work'
      required:
        - username
        - token
      properties:
        username:
          type: string
        token:
          type: string

    ErrorDescription:
      type: object
      description: 'Error description'
      properties:
        field:
          type: string
        error:
          type: string

    ErrorResponse:
      type: object
      description: 'Error response'
      properties:
        message:
          type: string

    PhoneDto:
      type: object
      description: 'Phone number'
      required:
        - value
      properties:
        value:
          type: string
          minLength: 1
        id:
          type: integer
          format: int64

    ProfileDto:
      type: object
      description: 'User profile'
      required:
        - cash
      properties:
        cash:
          type: number
        id:
          type: integer
          format: int64

    UserFullResponse:
      type: object
      description: 'Full user details'
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
        email:
          type: string
        username:
          type: string
        phones:
          type: array
          items:
            $ref: "#/components/schemas/PhoneDto"
        profile:
          $ref: "#/components/schemas/ProfileDto"

    ValidationErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            errors:
              type: array
              items:
                $ref: "#/components/schemas/ErrorDescription"

    UserRequest:
      type: object
      description: 'Request for create new user'
      required:
        - name
        - email
        - username
        - password
      properties:
        name:
          type: string
        email:
          type: string
        age:
          type: integer
          minimum: 12
          maximum: 85
        username:
          type: string
        password:
          type: string
        profile:
          $ref: "#/components/schemas/ProfileDto"
        phones:
          type: array
          items:
            $ref: "#/components/schemas/PhoneDto"

    ChangeEmailRequest:
      type: object
      description: 'Request for change user email'
      required:
        - email
      properties:
        email:
          type: string
